version: "3"
services:
  anyera:
    build:
      context: .
    volumes:
      - static_volume:/anyera/static
      - media_volume:/anyera/media
    env_file:
      - config/.env
    command: >
      sh -c "python manage.py collectstatic --noinput &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000 --noreload"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - config/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
    restart: unless-stopped
  nginx:
      build:
        context: ./nginx
      volumes:
        - static_volume:/anyera/static
        - media_volume:/anyera/media
      depends_on:
        - anyera
      ports:
        - "8000:80"
volumes:
  static_volume:
  media_volume:
  postgres-data: